### ISSUE TITLE
Encountered Issues while I used the skript

### ISSUE THREAD

**Issue by D3rK3vin** [jwdevos/guacamole-compose#1]
Hallo,
Ive used youre template and had some issues, I have fix them myself but I wanted to report them incase you want to fix them or write hints, if other people have the same problems as me.

Problems:
1. I had to swap the spaces before the commands with tabs

2. correct **docker compose** to **docker-compose**

3. Added an " at the end of this line
docker exec -it $(DB_CONTAINER_NAME) sh -c "cat initdb.sql | mysql -u root --password="EnterYourPassword" guacamole_db" 

P.S. could you say that you can add an password in the string.

Thank you for your work and have a nice day.

My file:
[Makefile.txt](https://github.com/jwdevos/guacamole-compose/files/10429413/Makefile.txt)

**Comment by jwdevos** [comment]
Hello D3rK3vin,

Thank you for checking out my project, and for taking the time to leave some comments. I fixed the tabs in the Makefile. I uploaded this small project via the GitHub webinterface, and it was set to spaces instead of tabs.

There is some difference between `docker compose` and `docker-compose`, but it depends on your installation. I updated the main page of this project with some additional information, should you be interested.

I also added some information about the mysql password. You don't even need to supply a password in the command, but in my case mysql kept asking for a password to be manually entered. In my case, supplying an empty password stopped mysql from asking, and the command just worked. Was the behavior different in your case?

Kind regards,
Jaap de Vos

**Comment by D3rK3vin** [comment]
Hello,

I am sorry for my delayed response. I didn't want to be disrespectful of your time.

I wasn't sure if there was any security risk involved when using no password, so I wanted to report it. However, I didn't encounter any errors or anything of the sort.

Best regards,
Kevin Laker
